<?php
$pageTitle = "Printable Report";
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Smart Food Report</title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<style>

body{
    margin:40px;
    font-family:Arial, sans-serif;
}

h1,h2,h3,h4,h5{
    text-align:center;
}

table{
    width:100%;
    border-collapse:collapse;
    margin-top:15px;
}

table th,
table td{
    border:1px solid #000;
    padding:8px;
    text-align:center;
}

.stats{
    display:flex;
    justify-content:space-between;
    margin:25px 0;
}

.stat-box{
    width:23%;
    border:1px solid #000;
    padding:15px;
    text-align:center;
}

.footer{
    text-align:center;
    margin-top:40px;
    font-size:14px;
}

@media print{

button{
display:none;
}

}

</style>

</head>

<body>
<form method="GET" action="<?php echo BASE_URL; ?>/index.php">
<input type="hidden" name="route" value="admin-reports">

<div class="row mb-4">

<div class="col-md-4">
<label><strong>Start Date:</strong></label>
<input type="date" 
       name="start_date" 
       class="form-control"
       value="<?php echo $_GET['start_date'] ?? ''; ?>">
</div>


<div class="col-md-4">
<label><strong>End Date:</strong></label>
<input type="date" 
       name="end_date" 
       class="form-control"
       value="<?php echo $_GET['end_date'] ?? ''; ?>">
</div>


<div class="col-md-4 mt-4">
<button type="submit" class="btn btn-primary">
Generate Report
</button>
</div>

</div>

<button onclick="window.print()" class="btn btn-success float-end">
Print / Save as PDF
</button>

<h2>Smart Food Redistribution Platform</h2>

<h4>Admin Report</h4>

<hr>

<p><strong>Generated On :</strong> <?php echo date("d-m-Y h:i A"); ?></p>

<?php if($startDate && $endDate): ?>

<p>

<strong>Date Range :</strong>

<?php echo htmlspecialchars($startDate); ?>

to

<?php echo htmlspecialchars($endDate); ?>

</p>

<?php endif; ?>

<div class="stats">

<div class="stat-box">
<h5>Total Donations</h5>
<h3><?php echo $totalDonations; ?></h3>
</div>

<div class="stat-box">
<h5>Completed Donations</h5>
<h3><?php echo $completedDonations; ?></h3>
</div>

<div class="stat-box">
<h5>Total Requests</h5>
<h3><?php echo $totalRequests; ?></h3>
</div>

<div class="stat-box">
<h5>Approved Requests</h5>
<h3><?php echo $approvedRequests; ?></h3>
</div>

</div>

<h4>Recent Donations</h4>

<table>

<tr>

<th>Food</th>

<th>Donor</th>

<th>Status</th>

</tr>

<?php if(empty($donations)): ?>

<tr>

<td colspan="3">No Donations Found</td>

</tr>

<?php else: ?>

<?php foreach($donations as $donation): ?>

<tr>

<td><?php echo htmlspecialchars($donation['food_name']); ?></td>

<td><?php echo htmlspecialchars($donation['donor_name']); ?></td>

<td><?php echo ucfirst($donation['status']); ?></td>

</tr>

<?php endforeach; ?>

<?php endif; ?>

</table>

<br><br>

<h4>Recent Requests</h4>

<table>

<tr>

<th>Food</th>

<th>NGO</th>

<th>Status</th>

</tr>

<?php if(empty($requests)): ?>

<tr>

<td colspan="3">No Requests Found</td>

</tr>

<?php else: ?>

<?php foreach($requests as $request): ?>

<tr>

<td><?php echo htmlspecialchars($request['food_name']); ?></td>

<td><?php echo htmlspecialchars($request['ngo_name']); ?></td>

<td><?php echo ucfirst($request['status']); ?></td>

</tr>

<?php endforeach; ?>

<?php endif; ?>

</table>

<div class="footer">

<hr>

Generated by Food Bridge - Smart Food Redistribution Platform

</div>



</body>

</html>